"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Flashlight.py']
DATA_FILES = ['res']
OPTIONS = {'argv_emulation': False,
 'iconfile': 'Flashlight.icns',
'semi_standalone':'False',
'site_packages': True}
setup(
   app=APP, 
   data_files=DATA_FILES,
   options={'py2app': OPTIONS},
   packages=['fl'],
   setup_requires=['py2app'],
)
